version: "3.8"

services:
  db:
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password"
    env_file: .env
    volumes:
      - db_data_iwc:/var/lib/mysql
    restart: unless-stopped
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - wordpress_net
    expose:
      - 3306

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: unless-stopped
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress_data_iwc:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    networks:
      - wordpress_net

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - wordpress_net

volumes:
  db_data_iwc:
  wordpress_data_iwc:

networks:
  wordpress_net:
